// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  QueryClient,
  QueryCache,
  MutationCache,
  QueryObserver,
  InfiniteQueryObserver,
  QueriesObserver,
  MutationObserver,
  useQuery,
  useQueries,
  useInfiniteQuery,
  useMutation,
  useIsFetching,
  useIsMutating,
  QueryClientProvider,
  useQueryClient,
  QueryErrorResetBoundary,
  useQueryErrorResetBoundary,
  useIsRestoring,
  IsRestoringProvider
} from 'C:/code/flowm-license-ui/node_modules/.pnpm/@tanstack+react-query@4.36.1_react-dom@18.3.1_react@18.3.1/node_modules/@tanstack/react-query';
