// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { QueryClientConfig } from 'C:/code/flowm-license-ui/node_modules/.pnpm/@tanstack+react-query@4.36.1_react-dom@18.3.1_react@18.3.1/node_modules/@tanstack/react-query';

import { ReactQueryDevtools } from 'C:/code/flowm-license-ui/node_modules/.pnpm/@tanstack+react-query-devtools@4.36.1_@tanstack+react-query@4.36.1_react-dom@18.3.1_react@18.3.1/node_modules/@tanstack/react-query-devtools';


export type RuntimeReactQueryType = {
  
  devtool?: React.ComponentProps<typeof ReactQueryDevtools>

  queryClient?: QueryClientConfig
}
